/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/healthz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness probe
     * @description Returns 200 with {ok: true}. No auth.
     */
    get: operations['healthz'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/tokens': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List tokens (metadata only) */
    get: operations['listTokens'];
    put?: never;
    /**
     * Mint a new token
     * @description Returns the freshly-minted token including its plaintext
     *     `secret`. The secret appears in this response once and is
     *     never returned by any GET.
     */
    post: operations['createToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/tokens/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Revoke a token
     * @description Sets `revoked_at` on the row; tokens are not physically
     *     deleted. Returns the revoked id and the timestamp written.
     */
    delete: operations['deleteToken'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthzResponse: {
      /** @enum {boolean} */
      ok: true;
    };
    TokenCreateRequest: {
      name: string;
    };
    TokenCreateResponse: {
      id: string;
      name: string;
      prefix: string;
      secret: string;
      /** Format: date-time */
      created_at: string;
      /** @enum {string} */
      created_via: 'init' | 'first_run_mint' | 'dashboard' | 'cli';
    };
    TokenView: {
      id: string;
      name: string;
      prefix: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      last_used_at?: string | null;
      /** Format: date-time */
      revoked_at?: string | null;
      /** @enum {string} */
      created_via: 'init' | 'first_run_mint' | 'dashboard' | 'cli';
    };
    TokenListResponse: {
      tokens: components['schemas']['TokenView'][];
    };
    TokenDeleteResponse: {
      id: string;
      /** Format: date-time */
      revoked_at: string;
    };
    Problem: {
      /** @description Stable problem slug /problems/<name>. */
      type: string;
      title: string;
      status: number;
      detail?: string;
      instance?: string;
    };
  };
  responses: {
    /** @description Bearer missing, malformed, unknown, or revoked. */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Request body or query failed validation. */
    InvalidRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Request body exceeded the per-request 1 MiB cap. */
    PayloadTooLarge: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Token id does not exist or was already revoked. */
    TokenNotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Daemon is alive */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthzResponse'];
        };
      };
    };
  };
  listTokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All tokens, newest first */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenListResponse'];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  createToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenCreateRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenCreateResponse'];
        };
      };
      400: components['responses']['InvalidRequest'];
      401: components['responses']['Unauthorized'];
      413: components['responses']['PayloadTooLarge'];
    };
  };
  deleteToken: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revoked */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenDeleteResponse'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['TokenNotFound'];
    };
  };
}
