/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/healthz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness probe
     * @description Returns 200 with {ok: true}. No auth.
     */
    get: operations['healthz'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/tokens': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List tokens (metadata only) */
    get: operations['listTokens'];
    put?: never;
    /**
     * Mint a new token
     * @description Returns the freshly-minted token including its plaintext
     *     `secret`. The secret appears in this response once and is
     *     never returned by any GET.
     */
    post: operations['createToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/tokens/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Revoke a token
     * @description Sets `revoked_at` on the row; tokens are not physically
     *     deleted. Returns the revoked id and the timestamp written.
     */
    delete: operations['deleteToken'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/agents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List configured agent backends
     * @description Returns the 5 trimmed backends in canonical order
     *     (claude, copilot, codex, hermes, pi). `installed` reflects
     *     `exec.LookPath` success; `version` is the CLI version when
     *     the probe succeeds, otherwise empty.
     */
    get: operations['listAgents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/agents/{type}/exec': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start an agent run; stream NDJSON envelopes
     * @description Starts a single agent execution and streams docs/
     *     architecture/02 §5 envelopes as NDJSON
     *     (application/x-ndjson). One envelope per line, terminated
     *     by `\n`; the final line is always session_ended.
     */
    post: operations['execAgent'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List sessions
     * @description Returns sessions ordered by started_at DESC. status/before
     *     filter and limit are applied in SQL.
     */
    get: operations['listSessions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/sessions/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single session */
    get: operations['getSession'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/sessions/{id}/messages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Snapshot session envelope events
     * @description Snapshot mode only in 3.11b. follow=true returns 400
     *     problem+json; tail follow lands in a later phase (see
     *     docs/architecture/02 §6.4).
     */
    get: operations['getSessionMessages'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/sessions/{id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel a running session
     * @description 202 with `{id, status: "cancelled"}` for a running session.
     *     200 with `{id, status: "already_terminated"}` for a session
     *     already in a terminal state (idempotent).
     */
    post: operations['cancelSession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthzResponse: {
      /** @enum {boolean} */
      ok: true;
    };
    TokenCreateRequest: {
      name: string;
    };
    TokenCreateResponse: {
      id: string;
      name: string;
      prefix: string;
      secret: string;
      /** Format: date-time */
      created_at: string;
      /** @enum {string} */
      created_via: 'init' | 'first_run_mint' | 'dashboard' | 'cli';
    };
    TokenView: {
      id: string;
      name: string;
      prefix: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      last_used_at?: string | null;
      /** Format: date-time */
      revoked_at?: string | null;
      /** @enum {string} */
      created_via: 'init' | 'first_run_mint' | 'dashboard' | 'cli';
    };
    TokenListResponse: {
      tokens: components['schemas']['TokenView'][];
    };
    TokenDeleteResponse: {
      id: string;
      /** Format: date-time */
      revoked_at: string;
    };
    Agent: {
      /** @enum {string} */
      type: 'claude' | 'copilot' | 'codex' | 'hermes' | 'pi';
      installed: boolean;
      executable: string;
      version: string;
    };
    AgentListResponse: {
      agents: components['schemas']['Agent'][];
    };
    ExecRequest: {
      prompt: string;
      cwd?: string;
      model?: string;
      system_prompt?: string;
      thread_name?: string;
      max_turns?: number;
      timeout_ms?: number;
      semantic_inactivity_timeout_ms?: number;
      resume_session_id?: string;
      custom_args?: string[];
      mcp_config?: {
        [key: string]: unknown;
      };
      thinking_level?: string;
    };
    Envelope: {
      /** @enum {integer} */
      v: 1;
      seq: number;
      /** Format: date-time */
      ts: string;
      session_id: string;
      /** @enum {string} */
      type: 'session_started' | 'message' | 'usage' | 'error' | 'session_ended' | 'heartbeat';
      payload: {
        [key: string]: unknown;
      };
    };
    Session: {
      id: string;
      /** @enum {string} */
      backend_type: 'claude' | 'copilot' | 'codex' | 'hermes' | 'pi';
      backend_session_id: string;
      /** @enum {string} */
      status: 'running' | 'completed' | 'failed' | 'aborted' | 'timeout' | 'cancelled';
      /** Format: date-time */
      started_at: string;
      /** Format: date-time */
      ended_at: string | null;
      thread_name: string;
      model: string;
    };
    SessionListResponse: {
      sessions: components['schemas']['Session'][];
    };
    MessagesSnapshotResponse: {
      session_id: string;
      events: components['schemas']['Envelope'][];
      next_after_seq: number;
      has_more: boolean;
    };
    CancelResponse: {
      id: string;
      /** @enum {string} */
      status: 'cancelled' | 'already_terminated';
    };
    Problem: {
      /** @description Stable problem slug /problems/<name>. */
      type: string;
      title: string;
      status: number;
      detail?: string;
      instance?: string;
    };
  };
  responses: {
    /** @description Bearer missing, malformed, unknown, or revoked. */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Request body or query failed validation. */
    InvalidRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Request body exceeded the per-request 1 MiB cap. */
    PayloadTooLarge: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Token id does not exist or was already revoked. */
    TokenNotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Session id does not exist. */
    SessionNotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Daemon is alive */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthzResponse'];
        };
      };
    };
  };
  listTokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All tokens, newest first */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenListResponse'];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  createToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenCreateRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenCreateResponse'];
        };
      };
      400: components['responses']['InvalidRequest'];
      401: components['responses']['Unauthorized'];
      413: components['responses']['PayloadTooLarge'];
    };
  };
  deleteToken: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revoked */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenDeleteResponse'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['TokenNotFound'];
    };
  };
  listAgents: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Agent list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AgentListResponse'];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  execAgent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        type: 'claude' | 'copilot' | 'codex' | 'hermes' | 'pi';
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ExecRequest'];
      };
    };
    responses: {
      /** @description NDJSON stream of envelope events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/x-ndjson': components['schemas']['Envelope'];
        };
      };
      400: components['responses']['InvalidRequest'];
      401: components['responses']['Unauthorized'];
      /** @description Unknown backend type */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      413: components['responses']['PayloadTooLarge'];
      /** @description Internal failure before stream start */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Backend recognised but unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  listSessions: {
    parameters: {
      query?: {
        /**
         * @description Single status or CSV of statuses. One of running,
         *     completed, failed, aborted, timeout, cancelled.
         */
        status?: string;
        before?: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionListResponse'];
        };
      };
      400: components['responses']['InvalidRequest'];
      401: components['responses']['Unauthorized'];
    };
  };
  getSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session row */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Session'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['SessionNotFound'];
    };
  };
  getSessionMessages: {
    parameters: {
      query?: {
        after_seq?: number;
        limit?: number;
        /** @description CSV filter, e.g. message,session_ended */
        types?: string;
        follow?: 'false';
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Snapshot envelope page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessagesSnapshotResponse'];
        };
      };
      400: components['responses']['InvalidRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['SessionNotFound'];
    };
  };
  cancelSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Already terminated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CancelResponse'];
        };
      };
      /** @description Cancel request accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CancelResponse'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['SessionNotFound'];
    };
  };
}
